[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/landing.html"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/impressum.html"
  to = "/impressum.html"
  status = 200

[[redirects]]
  from = "/datenschutz.html"
  to = "/datenschutz.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
